/**
 * Calendar operation manifest — single source of truth.
 *
 * Permission classifier, dispatcher, capability validator, and tests
 * all read from this manifest. No three divergent tables.
 *
 * Blueprint §12: CalendarOperationSpec is the canonical spec per action.
 * Blueprint §13: complete risk mapping.
 */
import type { CalendarAction, CalendarOperationSpec } from "./types.js";

type OperationManifest = Record<Exclude<CalendarAction, "status">, CalendarOperationSpec>;

export const CALENDAR_OPERATIONS: OperationManifest = {
	// ── Read / query ────────────────────────────────────────────────
	calendars: {
		action: "calendars",
		gogCommand: ["calendar", "calendars"],
		exactCommand: "calendar.calendars",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	acl: {
		action: "acl",
		gogCommand: ["calendar", "acl"],
		exactCommand: "calendar.acl",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	alias_list: {
		action: "alias_list",
		gogCommand: ["calendar", "alias", "list"],
		exactCommand: "calendar.alias.list",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: false,
		requiresAuth: false,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 10_000,
	},
	events: {
		action: "events",
		gogCommand: ["calendar", "events"],
		exactCommand: "calendar.events",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	event: {
		action: "event",
		gogCommand: ["calendar", "event"],
		exactCommand: "calendar.event",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	event_raw: {
		action: "event_raw",
		gogCommand: ["calendar", "raw"],
		exactCommand: "calendar.raw",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	freebusy: {
		action: "freebusy",
		gogCommand: ["calendar", "freebusy"],
		exactCommand: "calendar.freebusy",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	propose_time: {
		action: "propose_time",
		gogCommand: ["calendar", "propose-time"],
		exactCommand: "calendar.propose-time",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	colors: {
		action: "colors",
		gogCommand: ["calendar", "colors"],
		exactCommand: "calendar.colors",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 10_000,
	},
	conflicts: {
		action: "conflicts",
		gogCommand: ["calendar", "conflicts"],
		exactCommand: "calendar.conflicts",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	changed: {
		action: "changed",
		gogCommand: ["calendar", "changed"],
		exactCommand: "calendar.changed",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	search: {
		action: "search",
		gogCommand: ["calendar", "search"],
		exactCommand: "calendar.search",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	time: {
		action: "time",
		gogCommand: ["calendar", "time"],
		exactCommand: "calendar.time",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 10_000,
	},
	users: {
		action: "users",
		gogCommand: ["calendar", "users"],
		exactCommand: "calendar.users",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	team: {
		action: "team",
		gogCommand: ["calendar", "team"],
		exactCommand: "calendar.team",
		risk: "read_only",
		mode: "read",
		readonly: true,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: false,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},

	// ── Local configuration writes ──────────────────────────────────
	alias_set: {
		action: "alias_set",
		gogCommand: ["calendar", "alias", "set"],
		exactCommand: "calendar.alias.set",
		risk: "write_local",
		mode: "local_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: false,
		requiresWriteReady: false,
		supportsDryRun: true,
		timeoutMs: 10_000,
	},
	alias_unset: {
		action: "alias_unset",
		gogCommand: ["calendar", "alias", "unset"],
		exactCommand: "calendar.alias.unset",
		risk: "write_local",
		mode: "local_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: false,
		requiresWriteReady: false,
		supportsDryRun: true,
		timeoutMs: 10_000,
	},

	// ── Calendar / list management ──────────────────────────────────
	subscribe: {
		action: "subscribe",
		gogCommand: ["calendar", "subscribe"],
		exactCommand: "calendar.subscribe",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	unsubscribe: {
		action: "unsubscribe",
		gogCommand: ["calendar", "unsubscribe"],
		exactCommand: "calendar.unsubscribe",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	create_calendar: {
		action: "create_calendar",
		gogCommand: ["calendar", "create-calendar"],
		exactCommand: "calendar.create-calendar",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	delete_calendar: {
		action: "delete_calendar",
		gogCommand: ["calendar", "delete-calendar"],
		exactCommand: "calendar.delete-calendar",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},

	// ── Event mutations ─────────────────────────────────────────────
	create: {
		action: "create",
		gogCommand: ["calendar", "create"],
		exactCommand: "calendar.create",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
	update: {
		action: "update",
		gogCommand: ["calendar", "update"],
		exactCommand: "calendar.update",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
	move: {
		action: "move",
		gogCommand: ["calendar", "move"],
		exactCommand: "calendar.move",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	delete: {
		action: "delete",
		gogCommand: ["calendar", "delete"],
		exactCommand: "calendar.delete",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: false,
		timeoutMs: 30_000,
	},
	respond: {
		action: "respond",
		gogCommand: ["calendar", "respond"],
		exactCommand: "calendar.respond",
		risk: "communication",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: true,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
	focus_time: {
		action: "focus_time",
		gogCommand: ["calendar", "focus-time"],
		exactCommand: "calendar.focus-time",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
	out_of_office: {
		action: "out_of_office",
		gogCommand: ["calendar", "out-of-office"],
		exactCommand: "calendar.out-of-office",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
	working_location: {
		action: "working_location",
		gogCommand: ["calendar", "working-location"],
		exactCommand: "calendar.working-location",
		risk: "scheduling",
		mode: "remote_write",
		readonly: false,
		wrapUntrusted: false,
		requiresAuth: true,
		requiresWriteReady: true,
		supportsDryRun: true,
		timeoutMs: 30_000,
	},
} as const;

/** Get the operation spec for an action, or undefined for unknown actions.
 *  "status" is a meta-action handled by the tool directly — it has no gog command. */
export function getOperationSpec(action: string): CalendarOperationSpec | undefined {
	if (action === "status") return undefined;
	return CALENDAR_OPERATIONS[action as keyof typeof CALENDAR_OPERATIONS];
}

/** All actions in the manifest (excluding the "status" meta-action). */
export const ALL_MANIFEST_ACTIONS = Object.keys(CALENDAR_OPERATIONS) as Array<Exclude<CalendarAction, "status">>;
