/**
 * kanban/ops.ts — the board/card CRUD surface shared by the /kanban command
 * and the kanban tool (both dispatch to the same `boardOps` object).
 *
 * Also owns: the active-board state, the debounced Markdown + static-HTML
 * regeneration (`scheduleRefresh`), and card-line formatting.
 *
 * Note: this module and worker.ts import from each other (ops.assign() spawns
 * a worker; the worker's completion path schedules a refresh). Both sides
 * only reference the other's export from inside function bodies that run
 * after both modules have finished loading, so the circular import is safe
 * under Node's ESM live-binding semantics — never at module-evaluation time.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { db_, waywiserHome } from "../utils/state.js";
import { generateStaticSnapshot } from "../kanban-html.js";
import { broadcastEvent } from "../kanban-server.js";
import {
	STATUSES,
	PRIORITIES,
	CARD_TYPES,
	CARD_ORDER,
	parseDue,
	isOverdue,
	slugify,
	nextCardId,
	getBoards,
	getAllBoards,
	getBoard,
	ensureBoard,
	getCards,
	getCard,
	type Status,
	type Priority,
	type CardType,
	type BoardRow,
	type CardRow,
	type OpResult,
} from "./shared.js";
import { spawnCard, waitCard, inFlight } from "./worker.js";

// Active board is per-process (not persisted across restarts); defaults to 'default'.
let activeBoardId = "default";
export function getActiveBoardId(): string {
	return activeBoardId;
}
export function setActiveBoardId(id: string): void {
	activeBoardId = id;
}

// ── card line (TUI/tool text) ────────────────────────────────────────
export function cardLine(c: CardRow): string {
	const pri = c.priority && c.priority !== "med" ? ` [${c.priority}]` : "";
	const typeTag = c.type === "idea" ? " 💡" : c.type === "bug" ? " 🐛" : "";
	const due = c.due
		? c.status === "done"
			? ` (was due ${c.due.slice(0, 16).replace("T", " ")})`
			: isOverdue(c)
				? ` (OVERDUE since ${c.due.slice(0, 16).replace("T", " ")})`
				: ` (due ${c.due.slice(0, 16).replace("T", " ")})`
		: "";
	return `${c.id}${pri} [${c.status}]${typeTag} ${c.title}${c.assignee ? ` → ${c.assignee}` : ""}${c.block_reason ? ` (block: ${c.block_reason})` : ""}${due}`;
}

// ── Markdown export ───────────────────────────────────────────────────
function fmtShortDate(iso: string): string {
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return iso.slice(0, 10);
	return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function mdCardLine(c: CardRow): string {
	const pri = c.priority && c.priority !== "med" ? ` \`${c.priority}\`` : "";
	const due = c.due ? ` \`due:${fmtShortDate(c.due)}\`` : "";
	const typeTag = c.type === "idea" ? " 💡idea" : c.type === "bug" ? " 🐛bug" : "";
	const overdueTag = isOverdue(c) ? " ⚠️OVERDUE" : "";
	const assignee = c.assignee ? ` → ${c.assignee}` : "";
	const line = `- [ ] **${c.id}** ${c.title}${pri}${due}${typeTag}${overdueTag}${assignee}`;
	const extra: string[] = [];
	if (c.status === "blocked" && c.block_reason) extra.push(`  > ${c.block_reason.slice(0, 200)}`);
	if (c.notes) extra.push(`  > ${c.notes.slice(0, 200)}`);
	if (c.report) extra.push(`  > Report: ${c.report.slice(0, 200)}`);
	return extra.length ? `${line}\n${extra.join("\n")}` : line;
}

export function generateMarkdown(board: BoardRow, cards: CardRow[]): string {
	const open = cards.filter((c) => c.status !== "done").length;
	const overdue = cards.filter((c) => isOverdue(c)).length;
	const done = cards.filter((c) => c.status === "done").length;

	const lines: string[] = [
		"<!-- generated by waywiser — edits will be overwritten on next board change -->",
		`# Board: ${board.name}`,
		"",
		`> ${open} open · ${overdue} overdue · ${done} done`,
	];

	const section = (title: string, status: Status): void => {
		const rows = cards.filter((c) => c.status === status);
		if (!rows.length) return;
		lines.push("", `## ${title}`, ...rows.map(mdCardLine));
	};
	section("⚡ Doing", "doing");
	section("📋 Todo", "todo");
	section("🔍 Review", "review");
	section("🔴 Blocked", "blocked");

	const doneRows = cards.filter((c) => c.status === "done");
	if (doneRows.length) {
		lines.push("", "## ✅ Done", ...doneRows.map((c) => `- [x] ~~${c.id} ${c.title}~~ · ${fmtShortDate(c.updated_at)}`));
	}

	return `${lines.join("\n")}\n`;
}

// ── debounced Markdown + static HTML regeneration ────────────────────
let refreshTimer: ReturnType<typeof setTimeout> | undefined;
export function scheduleRefresh(): void {
	if (refreshTimer) clearTimeout(refreshTimer);
	refreshTimer = setTimeout(() => {
		refreshTimer = undefined;
		try {
			const boards = getBoards();
			const cards = getCards();
			const boardsDir = path.join(waywiserHome(), "boards");
			fs.mkdirSync(boardsDir, { recursive: true });
			for (const board of boards) {
				const boardCards = cards.filter((c) => c.board_id === board.id);
				fs.writeFileSync(path.join(boardsDir, `${board.id}.md`), generateMarkdown(board, boardCards));
			}
			const html = generateStaticSnapshot(boards, cards, activeBoardId);
			fs.writeFileSync(path.join(waywiserHome(), "board.html"), html);
		} catch (e) {
			process.stderr.write(`waywiser/kanban: refresh failed: ${e instanceof Error ? e.message : String(e)}\n`);
		}
	}, 500);
}

export function stopRefreshTimer(): void {
	if (refreshTimer) {
		clearTimeout(refreshTimer);
		refreshTimer = undefined;
	}
}

// ── shared ops (command and tool both call these) ────────────────────
export const boardOps = {
	newCard(title: string, extra?: { priority?: string; due?: string; type?: string; board?: string }): OpResult {
		if (!title.trim()) return { ok: false, msg: "usage: new <title> [priority=low|med|high|critical] [due=@ISO|YYYY-MM-DD[Thh:mm]] [type=task|idea|bug]" };
		if (extra?.priority && !(PRIORITIES as readonly string[]).includes(extra.priority)) return { ok: false, msg: `priority must be one of ${PRIORITIES.join(", ")}` };
		if (extra?.type && !(CARD_TYPES as readonly string[]).includes(extra.type)) return { ok: false, msg: `type must be one of ${CARD_TYPES.join(", ")}` };
		const dueP = extra?.due ? parseDue(extra.due) : {};
		if (dueP.err) return { ok: false, msg: dueP.err };
		const boardId = extra?.board ? slugify(extra.board) : activeBoardId;
		ensureBoard(boardId);
		const id = nextCardId();
		db_()
			.prepare("INSERT INTO cards (id, board_id, title, type, status, priority, due) VALUES (?, ?, ?, ?, 'todo', ?, ?)")
			.run(id, boardId, title.trim(), (extra?.type as CardType) ?? "task", (extra?.priority as Priority) ?? "med", dueP.iso ?? null);
		const card = getCard(id)!;
		broadcastEvent("card_created", card);
		scheduleRefresh();
		return { ok: true, msg: cardLine(card) };
	},
	list(boardId?: string): OpResult {
		const cards = getCards(boardId ?? activeBoardId);
		return { ok: true, msg: cards.length ? cards.map(cardLine).join("\n") : "Board is empty." };
	},
	show(id: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		return {
			ok: true,
			msg:
				cardLine(c) +
				`\nboard: ${c.board_id}` +
				`\ncreated ${c.created_at}\nupdated ${c.updated_at}` +
				(c.notes ? `\nnotes: ${c.notes}` : "") +
				(c.report ? `\nreport: ${c.report}` : "") +
				(inFlight.has(c.id) ? `\n(worker running: ${c.worker_child ?? "?"})` : ""),
		};
	},
	move(id: string, status: string, boardId?: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		if (!(STATUSES as readonly string[]).includes(status)) return { ok: false, msg: `status must be one of ${STATUSES.join(", ")}` };
		if (inFlight.has(c.id) && status !== "doing") return { ok: false, msg: `${c.id} has a worker running — wait for it (action=wait) before moving it elsewhere` };
		const targetBoard = boardId ? slugify(boardId) : c.board_id;
		if (boardId) ensureBoard(targetBoard);
		const blockReason = status === "blocked" ? c.block_reason : null;
		db_().prepare("UPDATE cards SET status = ?, board_id = ?, block_reason = ?, updated_at = datetime('now') WHERE id = ?").run(status, targetBoard, blockReason, id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	assign(id: string, who: string, cwd: string, timeoutMs?: number): Promise<OpResult> {
		const c = getCard(id);
		if (!c) return Promise.resolve({ ok: false, msg: `no card ${id}` });
		if (!who) return Promise.resolve({ ok: false, msg: "usage: assign <id> <name|subagent>" });
		db_().prepare("UPDATE cards SET assignee = ?, updated_at = datetime('now') WHERE id = ?").run(who, id);
		if (who === "subagent") {
			const c2 = getCard(id)!;
			return spawnCard(c2, cwd, timeoutMs ?? 900_000).then((r) =>
				r.ok ? { ok: true, msg: `${cardLine(getCard(id)!)} — ${r.msg}` } : { ok: false, msg: `assign ${id} subagent: ${r.msg}` },
			);
		}
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return Promise.resolve({ ok: true, msg: cardLine(updated) });
	},
	block(id: string, reason: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		db_().prepare("UPDATE cards SET status = 'blocked', block_reason = ?, updated_at = datetime('now') WHERE id = ?").run(reason || "unspecified", id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	resume(id: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		db_().prepare("UPDATE cards SET status = 'todo', block_reason = NULL, updated_at = datetime('now') WHERE id = ?").run(id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	note(id: string, text: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		if (!text.trim()) return { ok: false, msg: "usage: note <id> <text>" };
		db_().prepare("UPDATE cards SET notes = ?, updated_at = datetime('now') WHERE id = ?").run(text.trim(), id);
		broadcastEvent("card_updated", getCard(id));
		scheduleRefresh();
		return { ok: true, msg: `note set on ${id}` };
	},
	report(id: string, text: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		if (!text.trim()) return { ok: false, msg: "usage: report <id> <text>" };
		db_().prepare("UPDATE cards SET report = ?, updated_at = datetime('now') WHERE id = ?").run(text.trim(), id);
		broadcastEvent("card_updated", getCard(id));
		scheduleRefresh();
		return { ok: true, msg: `report recorded on ${id}` };
	},
	setPriority(id: string, priority: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		if (!(PRIORITIES as readonly string[]).includes(priority)) return { ok: false, msg: `priority must be one of ${PRIORITIES.join(", ")}` };
		db_().prepare("UPDATE cards SET priority = ?, updated_at = datetime('now') WHERE id = ?").run(priority, id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	setDue(id: string, due: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		const p = parseDue(due);
		if (p.err) return { ok: false, msg: p.err };
		db_().prepare("UPDATE cards SET due = ?, updated_at = datetime('now') WHERE id = ?").run(p.iso!, id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	setType(id: string, type: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		if (!(CARD_TYPES as readonly string[]).includes(type)) return { ok: false, msg: `type must be one of ${CARD_TYPES.join(", ")}` };
		db_().prepare("UPDATE cards SET type = ?, updated_at = datetime('now') WHERE id = ?").run(type, id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	done(id: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		db_().prepare("UPDATE cards SET status = 'done', block_reason = NULL, updated_at = datetime('now') WHERE id = ?").run(id);
		const updated = getCard(id)!;
		broadcastEvent("card_updated", updated);
		scheduleRefresh();
		return { ok: true, msg: cardLine(updated) };
	},
	remove(id: string): OpResult {
		const c = getCard(id);
		if (!c) return { ok: false, msg: `no card ${id}` };
		db_().prepare("DELETE FROM cards WHERE id = ?").run(id);
		broadcastEvent("card_deleted", { id });
		scheduleRefresh();
		return { ok: true, msg: `removed ${id}` };
	},
	stats(boardId?: string): OpResult {
		const cards = getCards(boardId ?? activeBoardId);
		const counts: Record<string, number> = {};
		let overdue = 0;
		for (const c of cards) {
			counts[c.status] = (counts[c.status] ?? 0) + 1;
			if (isOverdue(c)) overdue += 1;
		}
		const parts = Object.keys(counts).filter((k) => counts[k] > 0).map((k) => `${k}=${counts[k]}`);
		if (overdue) parts.push(`overdue=${overdue}`);
		return { ok: true, msg: parts.join("  ") || "empty" };
	},
	clearDone(boardId?: string): OpResult {
		const b = boardId ?? activeBoardId;
		db_().prepare("DELETE FROM cards WHERE board_id = ? AND status = 'done'").run(b);
		broadcastEvent("board_changed", { boardId: b, action: "clear_done" });
		scheduleRefresh();
		return { ok: true, msg: "cleared done cards" };
	},
	wait(id: string, timeoutMs: number): Promise<OpResult> {
		return waitCard(id, timeoutMs).then((r) => {
			const c = getCard(id);
			if (!c) return { ok: false, msg: `no card ${id}` };
			if (r.stillRunning) return { ok: false, msg: `${id} still running after ${timeoutMs}ms — check later with list/show` };
			return { ok: true, msg: cardLine(c) + (c.report ? `\nreport: ${c.report}` : "") };
		});
	},
	// ── multi-board ops (Phase 2) ────────────────────────────────────
	boards(): OpResult {
		const boards = getAllBoards();
		if (!boards.length) return { ok: true, msg: "no boards" };
		const cards = getCards();
		const lines = boards.map((b) => {
			const bc = cards.filter((c) => c.board_id === b.id);
			const overdue = bc.filter((c) => isOverdue(c)).length;
			return `${b.id === activeBoardId ? "* " : "  "}${b.id} — ${b.name} (${bc.length} cards${overdue ? `, ${overdue} overdue` : ""})${b.archived ? " [archived]" : ""}`;
		});
		return { ok: true, msg: lines.join("\n") };
	},
	boardSwitch(idOrName: string): OpResult {
		if (!idOrName.trim()) return { ok: false, msg: "usage: board <name>" };
		const id = slugify(idOrName);
		const existing = getBoard(id);
		if (!existing) {
			db_().prepare("INSERT INTO boards (id, name) VALUES (?, ?)").run(id, idOrName.trim());
			broadcastEvent("board_changed", { boardId: id, action: "created" });
		} else if (existing.archived) {
			db_().prepare("UPDATE boards SET archived = 0 WHERE id = ?").run(id);
			broadcastEvent("board_changed", { boardId: id, action: "unarchived" });
		}
		activeBoardId = id;
		scheduleRefresh();
		return { ok: true, msg: `switched to board "${id}"` };
	},
	boardCreate(name: string, description?: string): OpResult {
		if (!name.trim()) return { ok: false, msg: "usage: board create <name> [description]" };
		const id = slugify(name);
		if (getBoard(id)) return { ok: false, msg: `board "${id}" already exists` };
		db_().prepare("INSERT INTO boards (id, name, description) VALUES (?, ?, ?)").run(id, name.trim(), description?.trim() || null);
		broadcastEvent("board_changed", { boardId: id, action: "created" });
		scheduleRefresh();
		return { ok: true, msg: `created board "${id}"` };
	},
	boardArchive(idOrName: string): OpResult {
		if (!idOrName.trim()) return { ok: false, msg: "usage: board archive <name>" };
		const id = slugify(idOrName);
		if (id === "default") return { ok: false, msg: "cannot archive the default board" };
		if (!getBoard(id)) return { ok: false, msg: `no board ${id}` };
		db_().prepare("UPDATE boards SET archived = 1 WHERE id = ?").run(id);
		if (activeBoardId === id) activeBoardId = "default";
		broadcastEvent("board_changed", { boardId: id, action: "archived" });
		scheduleRefresh();
		return { ok: true, msg: `archived board "${id}"` };
	},
	boardDelete(idOrName: string): OpResult {
		if (!idOrName.trim()) return { ok: false, msg: "usage: board delete <name>" };
		const id = slugify(idOrName);
		if (id === "default") return { ok: false, msg: "cannot delete the default board" };
		if (!getBoard(id)) return { ok: false, msg: `no board ${id}` };
		db_().prepare("DELETE FROM cards WHERE board_id = ?").run(id);
		db_().prepare("DELETE FROM boards WHERE id = ?").run(id);
		if (activeBoardId === id) activeBoardId = "default";
		broadcastEvent("board_changed", { boardId: id, action: "deleted" });
		scheduleRefresh();
		return { ok: true, msg: `deleted board "${id}" and its cards` };
	},
	search(query: string): OpResult {
		const q = query.trim();
		if (!q) return { ok: false, msg: "usage: search <query>" };
		const like = `%${q}%`;
		const rows = db_().prepare(`SELECT * FROM cards WHERE title LIKE ? OR notes LIKE ? OR report LIKE ? ${CARD_ORDER.replace("ORDER BY", "ORDER BY board_id,")}`).all(like, like, like) as CardRow[];
		if (!rows.length) return { ok: true, msg: `no cards matching "${q}"` };
		return { ok: true, msg: rows.map((c) => `[${c.board_id}] ${cardLine(c)}`).join("\n") };
	},
};
