[package]
name = "waywiser-security"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pi-types = { path = "../pi-types" }
waywiser-core = { path = "../waywiser-core" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono.workspace = true
uuid.workspace = true
